export const REQUEST = (type) => ({
  type,
});

export const SUCCESS = (type, payload) => ({
  type,
  payload,
});

export const FAILURE = (type, payload) => ({
  type,
  payload,
});

export const USER_REQUEST = {
  RESET_USER_DATA: "RESET_USER_DATA",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  GET_ALL_USERS_REQUEST: "GET_ALL_USERS_REQUEST",
  GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAILURE: "GET_ALL_USERS_FAILURE",

  REMOVE_USER_REQUEST: "REMOVE_USER_REQUEST",
  REMOVE_USER_SUCCESS: "REMOVE_USER_SUCCESS",
  REMOVE_USER_FAILURE: "REMOVE_USER_FAILURE",

  UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILURE: "GET_USER_FAILURE",

  CREATE_REQUEST: "CREATE_REQUEST",
  CREATE_SUCCESS: "CREATE_SUCCESS",
  CREATE_FAILURE: "CREATE_FAILURE",

  USER_BY_ROLE_REQUEST: "USER_BY_ROLE_REQUEST",
  USER_BY_ROLE_SUCCESS: "USER_BY_ROLE_SUCCESS",
  USER_BY_ROLE_FAILURE: "USER_BY_ROLE_FAILURE",

  GET_USERS_BY_TEAM_LEAD_REQUEST: "GET_USERS_BY_TEAM_LEAD_REQUEST",
  GET_USERS_BY_TEAM_LEAD_SUCCESS: "GET_USERS_BY_TEAM_LEAD_SUCCESS",
  GET_USERS_BY_TEAM_LEAD_FAILURE: "GET_USERS_BY_TEAM_LEAD_FAILURE",
};